language: minimal
notifications:
  email: false
services:
  - docker
os:
  - linux
before_install:
 - docker build -t image-test -f .travis.Dockerfile .

env:
  - BUILDTAGS='btrfs_noversion libdm_no_deferred_remove'
  - BUILDTAGS='btrfs_noversion libdm_no_deferred_remove containers_image_openpgp'

script: >
  sudo docker run -ti --rm
  -e TRAVIS=$TRAVIS -e TRAVIS_COMMIT_RANGE=$TRAVIS_COMMIT_RANGE
  -e TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST -e TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG
  -e TRAVIS_BRANCH=$TRAVIS_BRANCH -e TRAVIS_COMMIT=$TRAVIS_COMMIT
  -v $PWD:/src:Z -w /src
  image-test
  bash -c "make cross tools .gitvalidation validate test test-skopeo BUILDTAGS=\"$BUILDTAGS\""
